"use client";
// import type { Metadata } from "next";
import { robotoFlex, sourceSerif, greatVibes } from "@/utils/customFonts";
import { Toaster } from "react-hot-toast";
import "react-quill-new/dist/quill.snow.css";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import { SessionProvider } from "next-auth/react";
import Script from "next/script";
import PlausibleProvider from 'next-plausible'
import SideMenu from "./components/ui/sideMenu";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sl">
      <head>
        <Script
          id="cookieyes"
          src="https://cdn-cookieyes.com/client_data/4ea35c9889e0f2f54d3cfc92/script.js"
          strategy="afterInteractive"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${robotoFlex.className} ${sourceSerif.variable} ${greatVibes.variable}`}
      >
        <PlausibleProvider domain="osmrtnica.com">
          <SessionProvider>
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  margin: "15px",
                  background: "#828282",
                  color: "#fff",
                  fontSize: "15px",
                  width: "340px",
                },
                className: "text-base",
                duration: 3000,
              }}
            />
            {children}
          </SessionProvider>
        </PlausibleProvider>
      </body>
    </html>
  );
}
